name: Backup Repository to S3

on:
#  push:
#    branches:
#      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate bundling
          ref: ''

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

      - name: Create git bundle
        run: |
            BUNDLE_NAME="${{ github.event.repository.name }}.bundle"
            git bundle create "$BUNDLE_NAME" --all        

      - name: Upload to S3
        run: |
          aws s3 cp "${{ github.event.repository.name }}.bundle" "s3://istariai-codebase-backup/${{ github.event.repository.name }}.bundle"
